name: NerdMessage
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: Deaygo Jarkko
main: nu.nerd.nerdmessage.NerdMessage

permissions:
    nerdmessage.message:
        description: Send a message to another player
        default: true
    nerdmessage.me:
        description: Allow a user to send an action
        default: true
    nerdmessage.cmsg:
        default: op
        description: Send message to all users to get attention

    nerdmessage.ignore:
        default: true
        description: Temporarily ignore a player
    nerdmessage.ignore.bypass-msg:
        default: op
        description: Allows a user to bypass /ignore in personal messages.

commands:
    msg:
        aliases: [m, t, r, reply, tell]
        description: Send a message to a user.
        permission: nerdmessage.message
        usage: |
           /msg <user> <message>: Send a message to a player
    cmsg:
        description: Send message to all users to get attention
        permission: nerdmessage.cmsg
    me:
        description: Send an action
        permission: nerdmessage.me
    ignore:
        permission: nerdmessage.ignore
        description: Temporarily ignore a user.
    unignore:
        permission: nerdmessage.ignore
        description: Unignore an ignored user.

